skip_commits:
  message: /docs|Merge pull request.*/
image: Visual Studio 2019
install:
  - cmd: choco install dotnet-sdk --version=5.0.202
build_script:
  - dotnet build src --configuration Release
  - dotnet test src --configuration Release --no-build --no-restore
on_failure:
  - ps: Get-ChildItem *.received.* -recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
test: off
artifacts:
- path: nugets\*.nupkg